version: '3.7'
volumes:
  db-data:
  consul-data:
  grafana-data:
  nodered-data:
  export-data:
  portainer-data:
  vault-config-data:
  vault-file-data:
  xpert-manager-data:
  license-data:

# all common shared environment variables defined here:
x-common-env-variables: &common-variables
  EDGEX_SECURITY_SECRET_STORE: "false"
  edgex_registry_retry_count: 5
  edgex_registry_retry_wait: 5
  EDGEXPERT_LICENSE_PATH: /edgexpert/licenses/

services:

#################################################################
# Registry Services
#################################################################

  core-consul:
    image: consul:1.6.2
    container_name: edgex-core-consul
    hostname: edgex-core-consul
    command: "agent -server -bootstrap-expect=1 -client 0.0.0.0 -ui"
    networks:
      edgex-network:
        aliases:
        - edgex-core-consul
    ports:
    - "8400:8400"
    - "8500:8500"
    - "8600:8600"
    volumes:
    - type: volume
      source: consul-data
      target: /consul
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "20"

#################################################################
# Secrets and Security
#################################################################

  vault:
    image: iotechsys/${EX_REPO}-security-secrets-store:${EX_VER}
    container_name: edgex-vault
    hostname: edgex-vault
    command: >
      /usr/bin/dumb-init -- /bin/sh -c
      "touch /vault/config/assets/resp-init.json; chmod 744 /vault/config/assets/resp-init.json;
      exec /usr/local/bin/docker-entrypoint.sh server -log-level=info"
    networks:
      edgex-network:
        aliases:
        - edgex-vault
    ports:
    - "8200:8200"
    cap_add:
    - "IPC_LOCK"
    environment:
      <<: *common-variables
      VAULT_ADDR: https://edgex-vault:8200'
      VAULT_CONFIG_DIR: /vault/config
      VAULT_UI: "true"
    volumes:
    - type: volume
      source: vault-config-data
      target: /vault/config
    - type: volume
      source: vault-file-data
      target: /vault/file
    depends_on:
    - core-consul
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "20"

  vault-worker:
    image: iotechsys/${EX_REPO}-security-secretstore-setup:${EX_VER}
    container_name: edgex-vault-worker
    hostname: edgex-vault-worker
    entrypoint:
      sh -c "/security-secretstore-setup --init=true --vaultInterval=10"
    networks:
    - edgex-network
    environment:
      <<: *common-variables
    volumes:
    - type: volume
      source: vault-config-data
      target: /vault/config
    depends_on:
    - core-consul
    - vault
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "20"


#################################################################
# Database Services
#################################################################

  redis:
    image: iotechsys/${EX_REPO}-redis:1.6.0
    container_name: edgex-redis
    hostname: edgex-redis
    entrypoint: redis-server
    command: "/etc/redis/redis.conf --loglevel notice"
    networks:
    - edgex-network
    environment:
      <<: *common-variables
    ports:
    - "6379:6379"
    volumes:
    - type: volume
      source: db-data
      target: /data
    depends_on:
    - vault
    - vault-worker
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "20"

#################################################################
# Core Services
#################################################################

  core-metadata:
    image: iotechsys/${EX_REPO}-core-metadata:${EX_VER}
    container_name: edgex-core-metadata
    hostname: edgex-core-metadata
    entrypoint: /core-metadata
    command: "--profile=docker --confdir=/res ${EX_CONSUL} ${EX_REG_ADDR}
              --setting=Logging/EnableRemote:${EX_REMOTE_LOGGING}"
    networks:
    - edgex-network
    ports:
      - "48081:48081"
    environment:
      <<: *common-variables
    volumes:
    - type: bind
      source: ./edgexpert/licenses
      target: /edgexpert/licenses/
      read_only: true
    - type: volume
      source: vault-config-data
      target: /vault/config
    depends_on:
      - support-logging
      - redis
      - vault
      - vault-worker
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "20"

  core-data:
    image: iotechsys/${EX_REPO}-core-data:${EX_VER}
    container_name: edgex-core-data
    hostname: edgex-core-data
    entrypoint: /core-data
    command: "--profile=docker --confdir=/res ${EX_CONSUL} ${EX_REG_ADDR}
              --setting=Logging/EnableRemote:${EX_REMOTE_LOGGING}"
    networks:
    - edgex-network
    ports:
      - "48080:48080"
      - "5563:5563"
    environment:
      <<: *common-variables
    volumes:
    - type: bind
      source: ./edgexpert/licenses
      target: /edgexpert/licenses/
      read_only: true
    - type: volume
      source: vault-config-data
      target: /vault/config
    depends_on:
      - support-logging
      - redis
      - vault
      - vault-worker
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "20"

  core-command:
    image: iotechsys/${EX_REPO}-core-command:${EX_VER}
    container_name: edgex-core-command
    hostname: edgex-core-command
    entrypoint: /core-command
    command: "--profile=docker --confdir=/res ${EX_CONSUL} ${EX_REG_ADDR}
              --setting=Logging/EnableRemote:${EX_REMOTE_LOGGING}"
    networks:
    - edgex-network
    ports:
      - "48082:48082"
    environment:
      <<: *common-variables
    volumes:
    - type: bind
      source: ./edgexpert/licenses
      target: /edgexpert/licenses/
      read_only: true
    - type: volume
      source: vault-config-data
      target: /vault/config
    depends_on:
      - core-metadata
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "20"

#################################################################
# Export Services
#################################################################

  export-client:
    image: iotechsys/${EX_REPO}-export-client:${EX_VER}
    container_name: edgex-export-client
    hostname: edgex-export-client
    entrypoint: /export-client
    command: "--profile=docker --confdir=/res ${EX_CONSUL} ${EX_REG_ADDR}
              --setting=Logging/EnableRemote:${EX_REMOTE_LOGGING}"
    networks:
    - edgex-network
    ports:
      - "48071:48071"
    environment:
      <<: *common-variables
    volumes:
    - type: bind
      source: ./edgexpert/licenses
      target: /edgexpert/licenses/
      read_only: true
    - type: volume
      source: vault-config-data
      target: /vault/config
    depends_on:
      - core-data
      - vault
      - vault-worker
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "20"

  export-distro:
    image: iotechsys/${EX_REPO}-export-distro:${EX_VER}
    container_name: edgex-export-distro
    hostname: edgex-export-distro
    entrypoint: /export-distro
    command: "--profile=docker --confdir=/res ${EX_CONSUL} ${EX_REG_ADDR}
              --setting=Logging/EnableRemote:${EX_REMOTE_LOGGING}"
    networks:
    - edgex-network
    ports:
      - "48070:48070"
    environment:
      <<: *common-variables
      Certificates_MQTTS_Cert: 'dummy.crt'
      Certificates_MQTTS_Key: 'dummy.key'
      Certificates_AWS_Cert: 'dummy.crt'
      Certificates_AWS_Key: 'dummy.key'
    volumes:
    - type: volume
      source: export-data
      target: /export/keys
    - type: bind
      source: ./edgexpert/licenses
      target: /edgexpert/licenses/
      read_only: true
    - type: volume
      source: vault-config-data
      target: /vault/config
    depends_on:
      - export-client
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "20"

#################################################################
# Supporting Services
#################################################################

  support-notifications:
    image: iotechsys/${EX_REPO}-support-notifications:${EX_VER}
    container_name: edgex-support-notifications
    hostname: edgex-support-notifications
    entrypoint: /support-notifications
    command: "--profile=docker --confdir=/res ${EX_CONSUL} ${EX_REG_ADDR}
              --setting=Logging/EnableRemote:${EX_REMOTE_LOGGING}"
    networks:
    - edgex-network
    ports:
    - "48060:48060"
    environment:
      <<: *common-variables
    volumes:
    - type: bind
      source: ./edgexpert/licenses
      target: /edgexpert/licenses/
      read_only: true
    - type: volume
      source: vault-config-data
      target: /vault/config
    depends_on:
    - core-metadata
    - redis
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "20"

  support-scheduler:
    image: iotechsys/${EX_REPO}-support-scheduler:${EX_VER}
    container_name: edgex-support-scheduler
    hostname: edgex-support-scheduler
    entrypoint: /support-scheduler
    command: "--profile=docker --confdir=/res ${EX_CONSUL} ${EX_REG_ADDR}
              --setting=Logging/EnableRemote:${EX_REMOTE_LOGGING}"
    networks:
    - edgex-network
    ports:
    - "48085:48085"
    environment:
      <<: *common-variables
    volumes:
    - type: bind
      source: ./edgexpert/licenses
      target: /edgexpert/licenses/
      read_only: true
    - type: volume
      source: vault-config-data
      target: /vault/config
    depends_on:
    - core-metadata
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "20"

  support-logging:
    image: iotechsys/${EX_REPO}-support-logging:${EX_VER}
    container_name: edgex-support-logging
    hostname: edgex-support-logging
    entrypoint: /support-logging
    command: "--profile=docker --confdir=/res ${EX_CONSUL} ${EX_REG_ADDR}
              --setting=Logging/EnableRemote:${EX_REMOTE_LOGGING}"
    networks:
    - edgex-network
    ports:
    - "48061:48061"
    environment:
      <<: *common-variables
    volumes:
    - type: bind
      source: ./edgexpert/licenses
      target: /edgexpert/licenses/
      read_only: true
    - type: volume
      source: vault-config-data
      target: /vault/config
    depends_on:
    - redis
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "20"

#################################################################
# Management Console
#################################################################

  xpert-manager:
    image: iotechsys/${EX_REPO}-iotech-manager:1.6.0
    container_name: xpert-manager
    hostname: xpert-manager
    entrypoint: /root/go-ui-server
    command: "--multi-user=${EX_VAULT}"
    networks:
    - edgex-network
    ports:
    - "8080:8080"
    environment:
      <<: *common-variables
      VAULT_CA_FILE_PATH: /vault/config/pki/EdgeXFoundryCA/EdgeXFoundryCA.pem
      VAULT_TOKEN_FILE_PATH: /vault/config/assets/resp-init.json
      VAULT_ADDR: https://edgex-vault:8200
    volumes:
    - type: volume
      source: vault-config-data
      target: /vault/config
    - type: volume
      source: xpert-manager-data
      target: /xpert-manager/data
    depends_on:
    - core-metadata
    - core-data
    - core-command
    - vault
    - vault-worker
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "20"

#################################################################
# Device Services
#################################################################

  device-mqtt:
    image: iotechsys/${EX_REPO}-device-mqtt:1.6.0
    container_name: edgex-device-mqtt
    hostname: edgex-device-mqtt
    entrypoint: /device-mqtt
    command: "--profile=docker --confdir=/res --setting=Logging/EnableRemote:${EX_REMOTE_LOGGING}
              ${EX_CONSUL} ${EX_REG_ADDR}"
    networks:
    - edgex-network
    ports:
      - "49982:49982"
    environment:
      <<: *common-variables
    volumes:
    - type: bind
      source: ./edgexpert/licenses
      target: /edgexpert/licenses/
      read_only: true
    depends_on:
      - core-metadata
      - core-data
      - core-command
      - mqtt-broker
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "20"

  device-virtual:
    image: iotechsys/${EX_REPO}-device-virtual:1.6.0
    container_name: edgex-device-virtual
    hostname: edgex-device-virtual
    entrypoint: /device-virtual
    command: "--profile=docker --confdir=/res --setting=Logging/EnableRemote:${EX_REMOTE_LOGGING}
              ${EX_CONSUL} ${EX_REG_ADDR}"
    networks:
    - edgex-network
    ports:
      - "49990:49990"
    environment:
      <<: *common-variables
    depends_on:
      - core-metadata
      - core-data
      - core-command
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "20"

#################################################################
# Tools
#################################################################

  mqtt-broker:
    image: iotechsys/${EX_REPO}-mqtt-broker:1.6.0
    container_name: mqtt-broker
    hostname: mqtt-broker
    networks:
    - edgex-network
    ports:
      - "1883:1883"
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "20"

networks:
  edgex-network:
    driver: "bridge"
...