version: '3.7'
volumes:
  db-data:
  consul-data:
  grafana-data:
  nodered-data:
  export-data:
  portainer-data:
  vault-data:

services:

#################################################################
# Registry Services
#################################################################

  core-consul:
    image: consul:1.4.0
    ports:
    - "8400:8400"
    - "8500:8500"
    - "8600:8600"
    container_name: edgex-core-consul
    hostname: edgex-core-consul
    networks:
      edgex-network:
        aliases:
        - edgex-core-consul
    volumes:
    - type: volume
      source: consul-data
      target: /consul
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "20"

#################################################################
# Database Services
#################################################################

  redis:
    image: iotech-${EX_REPO}.jfrog.io/redis-${EX_ARCH}:${EX_VER}
    entrypoint: redis-server /etc/redis/redis.conf --loglevel notice
    ports:
    - "6379:6379"
    container_name: edgex-redis
    hostname: edgex-redis
    networks:
    - edgex-network
    volumes:
    - type: volume
      source: db-data
      target: /data
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "20"

#################################################################
# Core Services
#################################################################

  core-metadata:
    image: iotech-${EX_REPO}.jfrog.io/core-metadata-go-${EX_ARCH}:${EX_VER}
    entrypoint: /core-metadata --registry=${EX_CONSUL} --profile=docker --confdir=/res
      --setting=Logging/EnableRemote:${EX_REMOTE_LOGGING}
    ports:
      - "48081:48081"
    container_name: edgex-core-metadata
    hostname: edgex-core-metadata
    networks:
      - edgex-network
    volumes:
    - type: bind
      source: ./edgexpert/licenses
      target: /edgexpert/licenses/
      read_only: true
    depends_on:
      - support-logging
      - redis
    environment:
    - EDGEXPERT_LICENSE_PATH=/edgexpert/licenses/
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "20"

  core-data:
    image: iotech-${EX_REPO}.jfrog.io/core-data-go-${EX_ARCH}:${EX_VER}
    entrypoint: /core-data --registry=${EX_CONSUL} --profile=docker --confdir=/res
      --setting=Logging/EnableRemote:${EX_REMOTE_LOGGING}
    ports:
      - "48080:48080"
      - "5563:5563"
    container_name: edgex-core-data
    hostname: edgex-core-data
    networks:
      - edgex-network
    volumes:
    - type: bind
      source: ./edgexpert/licenses
      target: /edgexpert/licenses/
      read_only: true
    depends_on:
      - support-logging
      - redis
    environment:
    - EDGEXPERT_LICENSE_PATH=/edgexpert/licenses/
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "20"

  core-command:
    image: iotech-${EX_REPO}.jfrog.io/core-command-go-${EX_ARCH}:${EX_VER}
    entrypoint: /core-command --registry=${EX_CONSUL} --profile=docker --confdir=/res
      --setting=Logging/EnableRemote:${EX_REMOTE_LOGGING}
    ports:
      - "48082:48082"
    container_name: edgex-core-command
    hostname: edgex-core-command
    networks:
      - edgex-network
    volumes:
    - type: bind
      source: ./edgexpert/licenses
      target: /edgexpert/licenses/
      read_only: true
    depends_on:
      - core-metadata
    environment:
    - EDGEXPERT_LICENSE_PATH=/edgexpert/licenses/
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "20"

#################################################################
# Export Services
#################################################################

  export-client:
    image: iotech-${EX_REPO}.jfrog.io/export-client-go-${EX_ARCH}:${EX_VER}
    entrypoint: /export-client --registry=${EX_CONSUL} --profile=docker --confdir=/res
      --setting=Logging/EnableRemote:${EX_REMOTE_LOGGING}
    ports:
      - "48071:48071"
    container_name: edgex-export-client
    hostname: edgex-export-client
    networks:
      - edgex-network
    volumes:
    - type: bind
      source: ./edgexpert/licenses
      target: /edgexpert/licenses/
      read_only: true
    depends_on:
      - core-data
    environment:
      - EXPORT_CLIENT_DISTRO_HOST=edgex-export-distro
      - EXPORT_CLIENT_CONSUL_HOST=edgex-core-consul
      - EDGEXPERT_LICENSE_PATH=/edgexpert/licenses/
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "20"

  export-distro:
    image: iotech-${EX_REPO}.jfrog.io/export-distro-go-${EX_ARCH}:${EX_VER}
    entrypoint: /export-distro --registry=${EX_CONSUL} --profile=docker --confdir=/res
      --setting=Logging/EnableRemote:${EX_REMOTE_LOGGING}
    ports:
      - "48070:48070"
    container_name: edgex-export-distro
    hostname: edgex-export-distro
    networks:
      - edgex-network
    volumes:
    - type: volume
      source: export-data
      target: /export/keys
    - type: bind
      source: ./edgexpert/licenses
      target: /edgexpert/licenses/
      read_only: true
    depends_on:
       - export-client
    environment:
      - EXPORT_DISTRO_CLIENT_HOST=edgex-export-client
      - EXPORT_DISTRO_DATA_HOST=edgex-core-data
      - EXPORT_DISTRO_CONSUL_HOST=edgex-core-consul
      - EXPORT_DISTRO_MQTTS_CERT_FILE=none
      - EXPORT_DISTRO_MQTTS_KEY_FILE=none
      - EDGEXPERT_LICENSE_PATH=/edgexpert/licenses/
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "20"

#################################################################
# Supporting Services
#################################################################

  support-notifications:
    image: iotech-${EX_REPO}.jfrog.io/support-notifications-go-${EX_ARCH}:${EX_VER}
    entrypoint: /support-notifications --registry=${EX_CONSUL} --profile=docker --confdir=/res
      --setting=Logging/EnableRemote:${EX_REMOTE_LOGGING}
    ports:
    - "48060:48060"
    container_name: edgex-support-notifications
    hostname: edgex-support-notifications
    networks:
    - edgex-network
    volumes:
    - type: bind
      source: ./edgexpert/licenses
      target: /edgexpert/licenses/
      read_only: true
    depends_on:
    - core-metadata
    - redis
    environment:
    - EDGEXPERT_LICENSE_PATH=/edgexpert/licenses/
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "20"

  support-scheduler:
    image: iotech-${EX_REPO}.jfrog.io/support-scheduler-go-${EX_ARCH}:${EX_VER}
    entrypoint: /support-scheduler --registry=${EX_CONSUL} --profile=docker --confdir=/res
      --setting=Logging/EnableRemote:${EX_REMOTE_LOGGING}
    ports:
    - "48085:48085"
    container_name: edgex-support-scheduler
    hostname: edgex-support-scheduler
    networks:
    - edgex-network
    volumes:
    - type: bind
      source: ./edgexpert/licenses
      target: /edgexpert/licenses/
      read_only: true
    depends_on:
    - core-metadata
    environment:
    - EDGEXPERT_LICENSE_PATH=/edgexpert/licenses/
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "20"

  # sys-mgmt:
  #   image: iotech-${EX_REPO}.jfrog.io/sys-mgmt-agent-${EX_ARCH}:${EX_VER}
  #   ports:
  #   - "48090:48090"
  #   container_name: edgex-sys-mgmt
  #   hostname: edgex-sys-mgmt
  #   networks:
  #   - edgex-network
  #   depends_on:
  #   - core-consul
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10mb"
  #       max-file: "20"

  support-logging:
    image: iotech-${EX_REPO}.jfrog.io/support-logging-go-${EX_ARCH}:${EX_VER}
    entrypoint: /support-logging --registry=${EX_CONSUL} --profile=docker --confdir=/res
    ports:
    - "48061:48061"
    container_name: edgex-support-logging
    hostname: edgex-support-logging
    networks:
    - edgex-network
    volumes:
    - type: bind
      source: ./edgexpert/licenses
      target: /edgexpert/licenses/
      read_only: true
    depends_on:
    - redis
    environment:
    - EDGEXPERT_LICENSE_PATH=/edgexpert/licenses/
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "20"

#################################################################
# Management Console
#################################################################

  xpert-manager:
    image: iotech-${EX_REPO}.jfrog.io/iotech-manager-${EX_ARCH}:${EX_VER}
    ports:
      - "8080:8080"
    container_name: xpert-manager
    hostname: xpert-manager
    networks:
      - edgex-network
    depends_on:
      - core-metadata
      - core-data
      - core-command
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "20"

#################################################################
# Secrets and Security
#################################################################

  # vault:
  #   image: iotech-${EX_REPO}.jfrog.io/edgex-vault-${EX_ARCH}:${EX_VER}
  #   container_name: edgex-vault
  #   hostname: edgex-vault
  #   networks:
  #   - edgex-network
  #   ports:
  #   - "8200:8200"
  #   cap_add:
  #   - "IPC_LOCK"
  #   command: "server -log-level=info"
  #   environment:
  #   - 'VAULT_ADDR=https://edgex-vault:8200'
  #   - 'VAULT_CONFIG_DIR=/vault/config'
  #   - 'VAULT_UI=true'
  #   volumes:
  #   - type: volume
  #     source: vault-data
  #     target: /vault/
  #   depends_on:
  #   - core-consul

  # vault-worker:
  #   image: iotech-${EX_REPO}.jfrog.io/edgex-vault-worker-${EX_ARCH}:${EX_VER}
  #   container_name: edgex-vault-worker
  #   hostname: edgex-vault-worker
  #   command: ["--init=true", "--debug=false", "--wait=10", "--insureskipverify=false"]
  #   networks:
  #   - edgex-network
  #   volumes:
  #   - type: volume
  #     source: vault-data
  #     target: /vault/
  #   depends_on:
  #   - core-consul
  #   - vault

#################################################################
# Device Services
#################################################################

  # device-opc-ua:
  #   image: iotech-${EX_REPO}.jfrog.io/device-opc-ua-c-${EX_ARCH}:${EX_VER}
  #   entrypoint: /device_opcua --confdir=/res --name=device-opcua ${EX_REG_ADDR}
  #   ports:
  #     - "49952:49952"
  #   container_name: edgex-device-opc-ua
  #   hostname: edgex-device-opc-ua
  #   networks:
  #     - edgex-network
  #   volumes:
  #   - type: bind
  #     source: ./edgexpert/licenses
  #     target: /edgexpert/licenses/
  #     read_only: true
  #   depends_on:
  #     - core-metadata
  #     - core-data
  #     - core-command
  #   environment:
  #     - EDGEXPERT_LICENSE_PATH=/edgexpert/licenses/
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10mb"
  #       max-file: "20"

  # device-bacnet-ip:
  #   image: iotech-${EX_REPO}.jfrog.io/device-bacnet-ip-${EX_ARCH}:${EX_VER}
  #   entrypoint: /device-bacnet-c --confdir=/res --name=device-bacnet-ip ${EX_REG_ADDR}
  #   ports:
  #     - "49901:49901"
  #   container_name: edgex-device-bacnet-ip
  #   hostname: edgex-device-bacnet-ip
  #   networks:
  #     - edgex-network
  #   volumes:
  #   - type: bind
  #     source: ./edgexpert/licenses
  #     target: /edgexpert/licenses/
  #     read_only: true
  #   depends_on:
  #     - core-metadata
  #     - core-data
  #     - core-command
  #   environment:
  #     - EDGEXPERT_LICENSE_PATH=/edgexpert/licenses/
  #     - BACNET_BBMD_ADDRESS=$BBMD_ADDRESS
  #     - BACNET_BBMD_PORT=$BBMD_PORT
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10mb"
  #       max-file: "20"

  # device-bacnet-mstp:
  #   image: iotech-${EX_REPO}.jfrog.io/device-bacnet-mstp-${EX_ARCH}:${EX_VER}
  #   entrypoint: /device-bacnet-c --confdir=/res --name=device-bacnet-mtsp ${EX_REG_ADDR}
  #   ports:
  #     - "49902:49902"
  #   container_name: edgex-device-bacnet-mstp
  #   hostname: edgex-device-bacnet-mstp
  #   networks:
  #     - edgex-network
  #   volumes:
  #   - type: bind
  #     source: ./edgexpert/licenses
  #     target: /edgexpert/licenses/
  #     read_only: true
  #   depends_on:
  #     - core-metadata
  #     - core-data
  #     - core-command
  #   environment:
  #     - EDGEXPERT_LICENSE_PATH=/edgexpert/licenses/
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10mb"
  #       max-file: "20"
#    devices:
#      - /dev/ttyUSB0

  device-virtual:
    image: iotech-${EX_REPO}.jfrog.io/device-virtual-go-${EX_ARCH}:${EX_VER}
    entrypoint: /device-virtual --profile=docker --confdir=/res ${EX_REG_ADDR}
      --setting=Logging/EnableRemote:${EX_REMOTE_LOGGING}
    ports:
      - "49990:49990"
    container_name: edgex-device-virtual
    hostname: edgex-device-virtual
    networks:
      - edgex-network
    depends_on:
      - core-metadata
      - core-data
      - core-command
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "20"

  # device-modbus:
  #   image: iotech-${EX_REPO}.jfrog.io/device-modbus-go-${EX_ARCH}:${EX_VER}
  #   entrypoint: /device-modbus --profile=docker --confdir=/res ${EX_REG_ADDR}
  #     --setting=Logging/EnableRemote:${EX_REMOTE_LOGGING}
  #   ports:
  #     - "49991:49991"
  #   container_name: edgex-device-modbus
  #   hostname: edgex-device-modbus
  #   networks:
  #     - edgex-network
  #   volumes:
  #   - type: bind
  #     source: ./edgexpert/licenses
  #     target: /edgexpert/licenses/
  #     read_only: true
  #   depends_on:
  #     - core-metadata
  #     - core-data
  #     - core-command
  #   environment:
  #     - EDGEXPERT_LICENSE_PATH=/edgexpert/licenses/
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10mb"
  #       max-file: "20"
  mqttbroker:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    networks:
      edgex-network:
        aliases:
          - mqttbroker
          
  device-mqtt:
    image: iotech-${EX_REPO}.jfrog.io/device-mqtt-go-${EX_ARCH}:${EX_VER}
    entrypoint: /device-mqtt --profile=docker --confdir=/res ${EX_REG_ADDR}
      --setting=Logging/EnableRemote:${EX_REMOTE_LOGGING}
    ports:
      - "49982:49982"
    container_name: edgex-device-mqtt
    hostname: edgex-device-mqtt
    networks:
      - edgex-network
    volumes:
    - type: bind
      source: ./edgexpert/licenses
      target: /edgexpert/licenses/
      read_only: true
    depends_on:
      - core-metadata
      - core-data
      - core-command
      - mqttbroker
    environment:
    - EDGEXPERT_LICENSE_PATH=/edgexpert/licenses/
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "20"

#   device-grove:
#     image: iotech-${EX_REPO}.jfrog.io/device-grove-${EX_ARCH}:${EX_VER}
#     entrypoint: /device-grove --confdir=/res --name=device-grove ${EX_REG_ADDR}
#     ports:
#       - "49992:49992"
#     devices:
# #     - /dev/i2c-5 # for UP Squared (x86, 64-bit)
#       - /dev/i2c-1 # for Raspberry Pi (arm 32, 64-bit)
#     container_name: edgex-device-grove
#     hostname: edgex-device-grove
#     networks:
#       - edgex-network
#     depends_on:
#       - core-metadata
#       - core-data
#       - core-command
#     logging:
#       driver: "json-file"
#       options:
#         max-size: "10mb"
#         max-file: "20"


networks:
  edgex-network:
    driver: "bridge"
...