version: '3.7'
volumes:
  db-data:
  consul-data:
  consul-config:
  # export
  export-data:
  # edgexpert
  grafana-data:
  nodered-data:
  portainer-data:
  xpert-manager-data:
  license-data:
  profile-modeling-data:


# all common shared environment variables defined here:
x-common-env-variables: &common-variables
  EDGEX_SECURITY_SECRET_STORE: "false"
  Registry_Host: edgex-core-consul
  Clients_Data_Host: edgex-core-data
  Clients_CoreData_Host: edgex-core-data
  Clients_Notifications_Host: edgex-support-notifications
  Clients_Metadata_Host: edgex-core-metadata
  Clients_Command_Host: edgex-core-command
  Clients_Scheduler_Host: edgex-support-scheduler
  Clients_RulesEngine_Host: kuiper
  Clients_VirtualDevice_Host: device-virtual
  Databases_Primary_Host: edgex-redis
  # logging
  Clients_Logging_Host: edgex-support-logging
  Logging_EnableRemote: ${EX_REMOTE_LOGGING}
  # v1.6
  edgex_registry_retry_count: 5
  edgex_registry_retry_wait: 5
  # license
  EDGEXPERT_LICENSE_PATH: /edgexpert/licenses/

services:

  #################################################################
  # Registry Services
  #################################################################

  consul:
    image: iotechsys/${EX_REPO}-consul:${EX_VER}
    container_name: consul
    hostname: consul
    ports:
      - "8400:8400"
      - "8500:8500"
    networks:
      edgex-network:
        aliases:
          - edgex-core-consul
    environment:
      - EDGEX_DB=redis
      - EDGEX_SECURE=false
    volumes:
      - consul-config:/consul/config:z
      - consul-data:/consul/data:z
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "20"

  #################################################################
  # Database Services
  #################################################################

  redis:
    image: iotechsys/${EX_REPO}-redis:${EX_VER}
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      edgex-network:
        aliases:
            - edgex-redis
    environment:
      <<: *common-variables
    command: redis-server /etc/redis/redis.conf
    volumes:
      - db-data:/data:z
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "20"

  #################################################################
  # Core Services
  #################################################################

  core-metadata:
    image: iotechsys/${EX_REPO}-core-metadata:${EX_VER}
    container_name: core-metadata
    hostname: core-metadata
    entrypoint: /core-metadata
    command: "--confdir=res ${EX_USE_REGISTRY} ${EX_USE_CP}"
    ports:
      - "48081:48081"
    networks:
      edgex-network:
        aliases:
          - edgex-core-metadata
    environment:
      <<: *common-variables
      Service_Host: core-metadata
      Notifications_Sender: core-metadata
      Notifications_PostDeviceChanges: ${EX_SUPPORT_NOTIFICATION}
    volumes:
      - ./edgexpert/licenses:/edgexpert/licenses:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "20"
    depends_on:
      - consul
      - redis
      - support-notifications

  core-data:
    image: iotechsys/${EX_REPO}-core-data:${EX_VER}
    container_name: core-data
    hostname: core-data
    entrypoint: /core-data
    command: "--confdir=res ${EX_USE_REGISTRY} ${EX_USE_CP}"
    ports:
      - "48080:48080"
      - "5563:5563"
    networks:
      edgex-network:
        aliases:
          - edgex-core-data
    environment:
      <<: *common-variables
      Service_Host: core-data
    volumes:
      - ./edgexpert/licenses:/edgexpert/licenses:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "20"
    depends_on:
      - consul
      - redis
      - core-metadata

  core-command:
    image: iotechsys/${EX_REPO}-core-command:${EX_VER}
    container_name: core-command
    hostname: core-command
    entrypoint: /core-command
    command: "--confdir=res ${EX_USE_REGISTRY} ${EX_USE_CP}"
    ports:
      - "48082:48082"
    networks:
      edgex-network:
        aliases:
          - edgex-core-command
    environment:
      <<: *common-variables
      Service_Host: core-command
    volumes:
      - ./edgexpert/licenses:/edgexpert/licenses:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "20"
    depends_on:
      - consul
      - redis
      - core-metadata

  #################################################################
  # Export Services
  #################################################################

  export-client:
    image: iotechsys/${EX_REPO}-export-client:${EX_VER}
    container_name: export-client
    hostname: export-client
    entrypoint: /export-client
    command: "--confdir=res ${EX_USE_REGISTRY} ${EX_USE_CP}"
    ports:
      - "48071:48071"
    networks:
      edgex-network:
        aliases:
          - edgex-export-client
    environment:
      <<: *common-variables
      Service_Host: export-client
      Clients_Distro_Host: export-distro
    volumes:
      - ./edgexpert/licenses:/edgexpert/licenses:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "20"
    depends_on:
      - core-data

  export-distro:
    image: iotechsys/${EX_REPO}-export-distro:${EX_VER}
    container_name: export-distro
    hostname: export-distro
    entrypoint: /export-distro
    command: "--confdir=res ${EX_USE_REGISTRY} ${EX_USE_CP}"
    ports:
      - "48070:48070"
    networks:
      edgex-network:
        aliases:
          - edgex-export-distro
    environment:
      <<: *common-variables
      Service_Host: export-distro
      Clients_Export_Host: export-client
      MessageQueue_Host: core-data
      Certificates_MQTTS_Cert: 'dummy.crt'
      Certificates_MQTTS_Key: 'dummy.key'
      Certificates_AWS_Cert: 'dummy.crt'
      Certificates_AWS_Key: 'dummy.key'
    volumes:
      - export-data:/export/keys
      - ./edgexpert/licenses:/edgexpert/licenses:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "20"
    depends_on:
      - export-client

  #################################################################
  # Application Services
  #################################################################

  app-service:
    image: iotechsys/${EX_REPO}-app-configurable:${EX_VER}
    container_name: app-service-${APP_NAME}
    hostname: app-service-${APP_NAME}
    ports:
      - "48097:48097"
    networks:
      edgex-network:
        aliases:
          - app-service-${APP_NAME}
    environment:
      - EDGEX_SECURITY_SECRET_STORE=false
      - Service_Host=app-service-${APP_NAME}
      - Registry_Host=edgex-core-consul
      - Clients_CoreData_Host=core-data
      - Clients_Logging_Host=support-logging
      - MessageBus_SubscribeHost_Host=core-data
      - Databases_Primary_Host=edgex-redis
      - Databases_Primary_Type=redisdb
      - Databases_Primary_Port=6379
    entrypoint: /app-service-configurable
    command: "--confdir=res --profile=${APP_NAME} ${EX_USE_REGISTRY} ${EX_USE_CP}"
    volumes:
      - ./config/app-service:/res
      - ./edgexpert/licenses:/edgexpert/licenses:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "20"

  #################################################################
  # Supporting Services
  #################################################################

  support-notifications:
    image: iotechsys/${EX_REPO}-support-notifications:${EX_VER}
    container_name: support-notifications
    hostname: support-notifications
    entrypoint: /support-notifications
    command: "--confdir=res ${EX_USE_REGISTRY} ${EX_USE_CP}"
    ports:
      - "48060:48060"
    networks:
      edgex-network:
        aliases:
          - edgex-support-notifications
    environment:
      <<: *common-variables
      Service_Host: support-notifications
    volumes:
      - ./edgexpert/licenses:/edgexpert/licenses:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "20"
    depends_on:
      - consul
      - redis

  support-scheduler:
    image: iotechsys/${EX_REPO}-support-scheduler:${EX_VER}
    container_name: support-scheduler
    hostname: support-scheduler
    entrypoint: /support-scheduler
    command: "--confdir=res ${EX_USE_REGISTRY} ${EX_USE_CP}"
    ports:
      - "48085:48085"
    networks:
      edgex-network:
        aliases:
          - edgex-support-scheduler
    environment:
      <<: *common-variables
      Service_Host: support-scheduler
      IntervalActions_ScrubPushed_Host: core-data
      IntervalActions_ScrubAged_Host: core-data
    volumes:
      - ./edgexpert/licenses:/edgexpert/licenses:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "20"
    depends_on:
      - consul
      - redis

  support-logging:
    image: iotechsys/${EX_REPO}-support-logging:${EX_VER}
    container_name: support-logging
    hostname: support-logging
    entrypoint: /support-logging
    command: "--confdir=res ${EX_USE_REGISTRY} ${EX_USE_CP}"
    ports:
      - "48061:48061"
    networks:
      edgex-network:
        aliases:
          - edgex-support-logging
    environment:
      <<: *common-variables
      Service_Host: support-logging
      Writable_Persistence: file
      Databases_Primary_Type: file
      Logging_EnableRemote: "false"
      Logging_File: "/edgex/log/edgex-support-logging.log"
    volumes:
      - ./edgexpert/licenses:/edgexpert/licenses:ro
    depends_on:
      - consul

  #################################################################
  # Management Console
  #################################################################

  xpert-manager:
    image: iotechsys/${EX_REPO}-iotech-manager:${EX_VER}
    container_name: xpert-manager
    hostname: xpert-manager
    entrypoint: /root/go-ui-server
    ports:
      - "8080:8080"
    networks:
      - edgex-network
    environment:
      <<: *common-variables
    volumes:
      #- vault-config:/vault/config
      - xpert-manager-data:/xpert-manager/data
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "20"
    depends_on:
      - core-metadata
      - core-data
      - core-command

  #################################################################
  # Device Services
  #################################################################

  device-virtual:
    image: iotechsys/${EX_REPO}-device-virtual:${EX_VER}
    container_name: device-virtual
    hostname: device-virtual
    entrypoint: /device-virtual
    command: "--confdir=res ${EX_USE_REGISTRY} ${EX_USE_CP}"
    ports:
      - "49990:49990"
    networks:
      edgex-network:
        aliases:
          - device-virtual
    environment:
      <<: *common-variables
      Service_Host: device-virtual
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "20"
    depends_on:
      - consul
      - core-data
      - core-metadata


  #################################################################
  # Tools
  #################################################################

  mqtt-broker:
    image: iotechsys/${EX_REPO}-mqtt-broker:${EX_VER}
    container_name: mqtt-broker
    hostname: mqtt-broker
    networks:
      - edgex-network
    ports:
      - "1883:1883"
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "20"

networks:
  edgex-network:
    driver: "bridge"
...
